# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://phonobyte.com
title: PhonoByte
email: phonobyte@gmail.com
author: PhonoByte
description: > # "Write an awesome description for your new site here. 
  Learning Voice Everyday.
copyright: 'Copyright &copy; 2020 PhonoByte. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/BytePhono
  - title: github
    url: https://github.com/phonobyte/
  - title: linkedin
    url: https://www.linkedin.com/company/phonobyte
